/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wares */
        get: operations["list_wares_api_v1_wares_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wares/{ware_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ware */
        get: operations["get_ware_api_v1_wares__ware_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faction-relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Faction Relations
         * @description List every faction-to-faction relation pair at gamestart — avoids N+1 queries.
         */
        get: operations["list_all_faction_relations_api_v1_faction_relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Factions
         * @description List all factions in the game catalog.
         */
        get: operations["list_factions_api_v1_factions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factions/{faction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Faction
         * @description Get detailed information for a specific faction.
         */
        get: operations["get_faction_api_v1_factions__faction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factions/{faction_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Faction Relations
         * @description List initial diplomatic relations for a faction (gamestart values only).
         */
        get: operations["list_faction_relations_api_v1_factions__faction_id__relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Licences
         * @description List all faction licences, optionally filtered by faction_id.
         */
        get: operations["list_licences_api_v1_licences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clusters */
        get: operations["list_clusters_api_v1_map_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sectors */
        get: operations["list_sectors_api_v1_map_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/sectors/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sector */
        get: operations["get_sector_api_v1_map_sectors__sector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gates */
        get: operations["list_gates_api_v1_map_gates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Zones */
        get: operations["list_zones_api_v1_map_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/sectors/{sector_id}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector Zones
         * @description List all zones available in a specific sector.
         */
        get: operations["get_sector_zones_api_v1_map_sectors__sector_id__zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Resources
         * @description List resource region entries. Filter by ware to find where a resource spawns.
         */
        get: operations["list_resources_api_v1_map_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/sectors/{sector_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector Resources
         * @description List all resources available in a specific sector.
         */
        get: operations["get_sector_resources_api_v1_map_sectors__sector_id__resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_api_v1_map_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/superhighways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Superhighways */
        get: operations["list_superhighways_api_v1_map_superhighways_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modules */
        get: operations["list_modules_api_v1_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module */
        get: operations["get_module_api_v1_modules__module_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ships
         * @description List all ships in the game catalog.
         */
        get: operations["list_ships_api_v1_ships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ships/{ship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ship
         * @description Get detailed stats for a specific ship.
         */
        get: operations["get_ship_api_v1_ships__ship_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/npc-stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Npc Stations
         * @description List NPC stations in the universe, optionally filtered by owner, tag, or sector.
         */
        get: operations["list_npc_stations_api_v1_npc_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/npc-stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Npc Station
         * @description Get full details for a specific NPC station including coordinates.
         */
        get: operations["get_npc_station_api_v1_npc_stations__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loadouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Loadouts
         * @description List loadout presets with full equipment. Filter by ship_macro to see loadouts for a specific ship.
         */
        get: operations["list_loadouts_api_v1_loadouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loadouts/{loadout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loadout
         * @description Get a specific loadout with its full equipment list.
         */
        get: operations["get_loadout_api_v1_loadouts__loadout_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment-mods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Equip Mods */
        get: operations["list_equip_mods_api_v1_equipment_mods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment-mods/{ware_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Equip Mod */
        get: operations["get_equip_mod_api_v1_equipment_mods__ware_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terraform/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Terraform Stats */
        get: operations["list_terraform_stats_api_v1_terraform_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terraform/project-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Terraform Project Groups */
        get: operations["list_terraform_project_groups_api_v1_terraform_project_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terraform/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Terraform Projects */
        get: operations["list_terraform_projects_api_v1_terraform_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terraform/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Terraform Project */
        get: operations["get_terraform_project_api_v1_terraform_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ware-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ware Groups
         * @description List all ware groups with display metadata.
         */
        get: operations["list_ware_groups_api_v1_ware_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ware-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ware Group */
        get: operations["get_ware_group_api_v1_ware_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diplomacy/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Diplo Actions
         * @description List all diplomatic agent actions.
         */
        get: operations["list_diplo_actions_api_v1_diplomacy_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diplomacy/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diplo Action */
        get: operations["get_diplo_action_api_v1_diplomacy_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diplomacy/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Diplo Gifts
         * @description List faction gift preferences. Filter by faction_id to find what a faction likes.
         */
        get: operations["list_diplo_gifts_api_v1_diplomacy_gifts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diplomacy/agent-ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agent Ranks
         * @description List agent rank thresholds and bonuses.
         */
        get: operations["list_agent_ranks_api_v1_diplomacy_agent_ranks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drops/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drop Lists
         * @description List all named drop tables.
         */
        get: operations["list_drop_lists_api_v1_drops_lists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drops/lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Drop List
         * @description Get a specific drop table with all its resolved ware entries.
         */
        get: operations["get_drop_list_api_v1_drops_lists__list_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drops/wares/{ware_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ware Drop Sources
         * @description Find all drop tables that can yield a specific ware (reverse lookup).
         */
        get: operations["get_ware_drop_sources_api_v1_drops_wares__ware_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRank */
        AgentRank: {
            /** Min Value */
            min_value: number;
            /** Name */
            name: string | null;
            /** Event Bonus */
            event_bonus: number | null;
            /** Icon */
            icon: string | null;
        };
        /** AllFactionRelation */
        AllFactionRelation: {
            /** Faction Id */
            faction_id: string;
            /** Other Faction Id */
            other_faction_id: string;
            /** Initial Relation */
            initial_relation: number;
        };
        /** BribeWare */
        BribeWare: {
            /** Ware Id */
            ware_id: string | null;
            /** Ware Tags */
            ware_tags: string | null;
            /** Amount */
            amount: number | null;
        };
        /** ClusterSummary */
        ClusterSummary: {
            /** Cluster Id */
            cluster_id: string;
            /** Macro Id */
            macro_id?: string | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Owner Faction */
            owner_faction?: string | null;
            /** Dlc */
            dlc?: string | null;
            /** Environment */
            environment?: string | null;
            /** Sun Class */
            sun_class?: string | null;
            /** Population Id */
            population_id?: string | null;
            /** Max Population */
            max_population?: number | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Z */
            z?: number | null;
        };
        /** DiploAction */
        DiploAction: {
            /** Action Id */
            action_id: string;
            /** Category */
            category: string | null;
            /** Name */
            name: string | null;
            /** Description */
            description: string | null;
            /** Hidden */
            hidden: number;
            /** Cost Influence */
            cost_influence: number | null;
            /** Cost Money */
            cost_money: number | null;
            /** Success Chance */
            success_chance: number | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Cooldown Sec */
            cooldown_sec: number | null;
            /** Agent Type */
            agent_type: string | null;
            /** Agent Experience */
            agent_experience: number | null;
            /** Risk */
            risk: string | null;
            /** Bribe Wares */
            bribe_wares: components["schemas"]["BribeWare"][];
        };
        /** DiploGift */
        DiploGift: {
            /** Ware Id */
            ware_id: string;
            /** Faction Id */
            faction_id: string;
        };
        /** DropEntry */
        DropEntry: {
            /** Ware Id */
            ware_id: string;
            /** Spawn Chance */
            spawn_chance: number | null;
            /** Item Chance */
            item_chance: number | null;
            /** Min Amount */
            min_amount: number;
            /** Max Amount */
            max_amount: number;
            /** Source Basket */
            source_basket: string | null;
        };
        /** DropList */
        DropList: {
            /** List Id */
            list_id: string;
            /** Category */
            category: string | null;
        };
        /** DropListDetail */
        DropListDetail: {
            /** List Id */
            list_id: string;
            /** Category */
            category: string | null;
            /** Wares */
            wares: components["schemas"]["DropEntry"][];
        };
        /** DropSource */
        DropSource: {
            /** List Id */
            list_id: string;
            /** Category */
            category: string | null;
            /** Spawn Chance */
            spawn_chance: number | null;
            /** Item Chance */
            item_chance: number | null;
            /** Min Amount */
            min_amount: number;
            /** Max Amount */
            max_amount: number;
            /** Source Basket */
            source_basket: string | null;
        };
        /** EquipModDetail */
        EquipModDetail: {
            /** Ware Id */
            ware_id: string;
            /** Name */
            name: string | null;
            /** Shortname */
            shortname: string | null;
            /** Category */
            category: string | null;
            /** Stat */
            stat: string | null;
            /** Quality */
            quality: number | null;
            /** Min Factor */
            min_factor: number | null;
            /** Max Factor */
            max_factor: number | null;
            /** Price Avg */
            price_avg: number | null;
            /** Description */
            description: string | null;
            /** Price Min */
            price_min: number | null;
            /** Price Max */
            price_max: number | null;
            /** Production Time */
            production_time: number | null;
        };
        /** EquipModSummary */
        EquipModSummary: {
            /** Ware Id */
            ware_id: string;
            /** Name */
            name: string | null;
            /** Shortname */
            shortname: string | null;
            /** Category */
            category: string | null;
            /** Stat */
            stat: string | null;
            /** Quality */
            quality: number | null;
            /** Min Factor */
            min_factor: number | null;
            /** Max Factor */
            max_factor: number | null;
            /** Price Avg */
            price_avg: number | null;
        };
        /** FactionDetail */
        FactionDetail: {
            /** Faction Id */
            faction_id: string;
            /** Name */
            name: string;
            /** Color Hex */
            color_hex: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Prefix Name */
            prefix_name?: string | null;
            /** Space Name */
            space_name?: string | null;
            /** Home Space Name */
            home_space_name?: string | null;
            /** Police Faction */
            police_faction?: string | null;
            /** Icon Active */
            icon_active?: string | null;
            /** Icon Inactive */
            icon_inactive?: string | null;
            /** Icon Banner */
            icon_banner?: string | null;
            /** Icon Url */
            icon_url?: string | null;
            /** Primary Race */
            primary_race: string | null;
            /** Description */
            description?: string | null;
            /** Behaviour Set */
            behaviour_set?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /** FactionLicence */
        FactionLicence: {
            /** Licence Type */
            licence_type: string;
            /** Faction Id */
            faction_id: string;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Precursor */
            precursor?: string | null;
            /** Price */
            price?: number | null;
            /** Min Relation */
            min_relation?: number | null;
        };
        /** FactionRelation */
        FactionRelation: {
            /** Other Faction Id */
            other_faction_id: string;
            /** Initial Relation */
            initial_relation: number;
        };
        /** FactionSummary */
        FactionSummary: {
            /** Faction Id */
            faction_id: string;
            /** Name */
            name: string;
            /** Color Hex */
            color_hex: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Prefix Name */
            prefix_name?: string | null;
            /** Space Name */
            space_name?: string | null;
            /** Home Space Name */
            home_space_name?: string | null;
            /** Police Faction */
            police_faction?: string | null;
            /** Icon Active */
            icon_active?: string | null;
            /** Icon Inactive */
            icon_inactive?: string | null;
            /** Icon Banner */
            icon_banner?: string | null;
            /** Icon Url */
            icon_url?: string | null;
        };
        /** GateSummary */
        GateSummary: {
            /** From Zone Id */
            from_zone_id: string;
            /** To Zone Id */
            to_zone_id: string;
            /** Kind */
            kind: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Api Version */
            api_version: string;
            /** Save Age Sec */
            save_age_sec: number | null;
            /** Game Version */
            game_version: string | null;
        };
        /** LoadoutDetail */
        LoadoutDetail: {
            /** Loadout Id */
            loadout_id: string;
            /** Ship Macro */
            ship_macro: string;
            /** Equipment */
            equipment: components["schemas"]["LoadoutEquipmentItem"][];
        };
        /** LoadoutEquipmentItem */
        LoadoutEquipmentItem: {
            /** Slot Path */
            slot_path: string | null;
            /** Macro */
            macro: string;
            /** Kind */
            kind: string;
            /** Optional */
            optional: boolean;
            /** Quantity */
            quantity: number | null;
        };
        /** ModuleDetail */
        ModuleDetail: {
            /** Module Id */
            module_id: string;
            /** Name */
            name: string;
            /** Dlc */
            dlc: string | null;
            /** Kind */
            kind: string | null;
            /** Size */
            size: string | null;
            /** Produces Ware Id */
            produces_ware_id: string | null;
            /** Storage Capacity */
            storage_capacity: number | null;
            /** Storage Type */
            storage_type: string | null;
            /** Drone Capacity */
            drone_capacity: number | null;
            /** Workforce Capacity */
            workforce_capacity: number | null;
            /** Icon Url */
            icon_url: string | null;
            /** Hull */
            hull: number | null;
            /** Explosiondamage */
            explosiondamage: number | null;
            /** Turrets S */
            turrets_s: number;
            /** Turrets M */
            turrets_m: number;
            /** Turrets L */
            turrets_l: number;
            /** Turrets Xl */
            turrets_xl: number;
            /** Shields S */
            shields_s: number;
            /** Shields M */
            shields_m: number;
            /** Shields L */
            shields_l: number;
            /** Shields Xl */
            shields_xl: number;
        };
        /** ModuleSummary */
        ModuleSummary: {
            /** Module Id */
            module_id: string;
            /** Name */
            name: string;
            /** Dlc */
            dlc: string | null;
            /** Kind */
            kind: string | null;
            /** Size */
            size: string | null;
            /** Produces Ware Id */
            produces_ware_id: string | null;
            /** Storage Capacity */
            storage_capacity: number | null;
            /** Storage Type */
            storage_type: string | null;
            /** Drone Capacity */
            drone_capacity: number | null;
            /** Workforce Capacity */
            workforce_capacity: number | null;
            /** Icon Url */
            icon_url: string | null;
        };
        /** NpcStationDetail */
        NpcStationDetail: {
            /** Station Id */
            station_id: string;
            /** Owner Faction */
            owner_faction: string | null;
            /** Race */
            race: string | null;
            /** Tags */
            tags: string[] | null;
            /** Location Sector */
            location_sector: string | null;
            /** Location Zone */
            location_zone: string | null;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
            /** Z */
            z: number | null;
        };
        /** NpcStationSummary */
        NpcStationSummary: {
            /** Station Id */
            station_id: string;
            /** Owner Faction */
            owner_faction: string | null;
            /** Race */
            race: string | null;
            /** Tags */
            tags: string[] | null;
            /** Location Sector */
            location_sector: string | null;
        };
        /** ProductionInput */
        ProductionInput: {
            /** Ware Id */
            ware_id: string;
            /** Amount */
            amount: number;
        };
        /** ProductionMethod */
        ProductionMethod: {
            /** Method */
            method: string;
            /** Time Sec */
            time_sec: number;
            /** Amount */
            amount: number;
            /** Workforce */
            workforce: number | null;
            /** Inputs */
            inputs: components["schemas"]["ProductionInput"][];
        };
        /** RegionSummary */
        RegionSummary: {
            /** Region Id */
            region_id: string;
            /** Cluster Id */
            cluster_id?: string | null;
            /** Sector Id */
            sector_id?: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Z */
            z?: number | null;
        };
        /** ResourceEntry */
        ResourceEntry: {
            /** Region Name */
            region_name: string;
            /** Sector Id */
            sector_id: string | null;
            /** Ware */
            ware: string;
            /** Yield Level */
            yield_level: string;
        };
        /** SectorSummary */
        SectorSummary: {
            /** Sector Id */
            sector_id: string;
            /** Cluster Id */
            cluster_id: string | null;
            /** Macro Id */
            macro_id?: string | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Owner Faction */
            owner_faction: string | null;
            /** Dlc */
            dlc?: string | null;
            /** Sunlight */
            sunlight?: number | null;
            /** Economy */
            economy?: number | null;
            /** Security */
            security?: number | null;
            /** Tags */
            tags?: string | null;
            /** Access Licence */
            access_licence?: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Z */
            z?: number | null;
        };
        /** ShipDetail */
        ShipDetail: {
            /** Ship Id */
            ship_id: string;
            /** Name */
            name: string;
            /** Dlc */
            dlc: string | null;
            /** Class Id */
            class_id: string | null;
            /** Ship Type */
            ship_type: string | null;
            /** Faction Id */
            faction_id: string | null;
            /** Role */
            role: string | null;
            /** Hull */
            hull: number | null;
            /** Cargo Volume */
            cargo_volume: number | null;
            /** Speed Max */
            speed_max: number | null;
            /** Icon Url */
            icon_url: string | null;
            /** Image Url */
            image_url: string | null;
            /** Description */
            description: string | null;
            /** Basename */
            basename: string | null;
            /** Secrecy Level */
            secrecy_level: number | null;
            /** Mass */
            mass: number | null;
            /** Drag Forward */
            drag_forward: number | null;
            /** Drag Reverse */
            drag_reverse: number | null;
            /** Drag Horizontal */
            drag_horizontal: number | null;
            /** Drag Vertical */
            drag_vertical: number | null;
            /** Drag Pitch */
            drag_pitch: number | null;
            /** Drag Yaw */
            drag_yaw: number | null;
            /** Drag Roll */
            drag_roll: number | null;
            /** Inertia Pitch */
            inertia_pitch: number | null;
            /** Inertia Yaw */
            inertia_yaw: number | null;
            /** Inertia Roll */
            inertia_roll: number | null;
            /** People Capacity */
            people_capacity: number | null;
            /** Missile Storage */
            missile_storage: number | null;
            /** Drone Storage */
            drone_storage: number | null;
            /** Countermeasure Storage */
            countermeasure_storage: number | null;
            /** Deployable Storage */
            deployable_storage: number | null;
            /** Weapons S */
            weapons_s: number;
            /** Weapons M */
            weapons_m: number;
            /** Weapons L */
            weapons_l: number;
            /** Weapons Xl */
            weapons_xl: number;
            /** Turrets S */
            turrets_s: number;
            /** Turrets M */
            turrets_m: number;
            /** Turrets L */
            turrets_l: number;
            /** Turrets Xl */
            turrets_xl: number;
            /** Shields S */
            shields_s: number;
            /** Shields M */
            shields_m: number;
            /** Shields L */
            shields_l: number;
            /** Shields Xl */
            shields_xl: number;
            /** Engines S */
            engines_s: number;
            /** Engines M */
            engines_m: number;
            /** Engines L */
            engines_l: number;
            /** Engines Xl */
            engines_xl: number;
            /** Software */
            software: components["schemas"]["ShipSoftware"][];
            /** Drop List Id */
            drop_list_id: string | null;
        };
        /** ShipSoftware */
        ShipSoftware: {
            /** Ware Id */
            ware_id: string;
            /** Compatible */
            compatible: number;
            /** Is Default */
            is_default: number;
        };
        /** ShipSummary */
        ShipSummary: {
            /** Ship Id */
            ship_id: string;
            /** Name */
            name: string;
            /** Dlc */
            dlc: string | null;
            /** Class Id */
            class_id: string | null;
            /** Ship Type */
            ship_type: string | null;
            /** Faction Id */
            faction_id: string | null;
            /** Role */
            role: string | null;
            /** Hull */
            hull: number | null;
            /** Cargo Volume */
            cargo_volume: number | null;
            /** Speed Max */
            speed_max: number | null;
            /** Icon Url */
            icon_url: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /** SuperhighwaySummary */
        SuperhighwaySummary: {
            /** From Zone Id */
            from_zone_id: string;
            /** To Zone Id */
            to_zone_id: string;
        };
        /** TerraformDelivery */
        TerraformDelivery: {
            /** Ship Macro */
            ship_macro: string;
            /** Amount */
            amount: number;
            /** Build Duration */
            build_duration: number | null;
        };
        /** TerraformEffect */
        TerraformEffect: {
            /** Stat */
            stat: string;
            /** Change */
            change: number;
            /** Min Val */
            min_val: number | null;
        };
        /** TerraformProjectDetail */
        TerraformProjectDetail: {
            /** Project Id */
            project_id: string;
            /** Group Id */
            group_id: string | null;
            /** Name */
            name: string | null;
            /** Description */
            description: string | null;
            /** Duration */
            duration: number | null;
            /** Repeat Cooldown */
            repeat_cooldown: number | null;
            /** Resilient */
            resilient: number | null;
            /** Resource Credits */
            resource_credits: number | null;
            /** Effects */
            effects: components["schemas"]["TerraformEffect"][];
            /** Resources */
            resources: components["schemas"]["TerraformResource"][];
            /** Deliveries */
            deliveries: components["schemas"]["TerraformDelivery"][];
        };
        /** TerraformProjectGroup */
        TerraformProjectGroup: {
            /** Group Id */
            group_id: string;
            /** Name */
            name: string | null;
        };
        /** TerraformProjectSummary */
        TerraformProjectSummary: {
            /** Project Id */
            project_id: string;
            /** Group Id */
            group_id: string | null;
            /** Name */
            name: string | null;
            /** Description */
            description: string | null;
            /** Duration */
            duration: number | null;
            /** Repeat Cooldown */
            repeat_cooldown: number | null;
            /** Resilient */
            resilient: number | null;
            /** Resource Credits */
            resource_credits: number | null;
        };
        /** TerraformResource */
        TerraformResource: {
            /** Ware Id */
            ware_id: string;
            /** Amount */
            amount: number;
        };
        /** TerraformStat */
        TerraformStat: {
            /** Stat Id */
            stat_id: string;
            /** Name */
            name: string | null;
            /** Icon */
            icon: string | null;
            /** Default Val */
            default_val: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WareDetail */
        WareDetail: {
            /** Ware Id */
            ware_id: string;
            /** Name */
            name: string;
            /** Group Id */
            group_id: string | null;
            /** Transport */
            transport: string | null;
            /** Volume */
            volume: number;
            /** Price Avg */
            price_avg: number | null;
            /** Tags */
            tags: string | null;
            /** Icon Url */
            icon_url: string | null;
            /** Price Min */
            price_min: number | null;
            /** Price Max */
            price_max: number | null;
            /** Storage Class */
            storage_class: string | null;
            /** Restriction Licence */
            restriction_licence?: string | null;
            /** Use Threshold */
            use_threshold?: number | null;
            /** Owners */
            owners: string[];
            /** Illegal Factions */
            illegal_factions: string[];
            /** Production */
            production: components["schemas"]["ProductionMethod"][];
        };
        /** WareGroup */
        WareGroup: {
            /** Group Id */
            group_id: string;
            /** Name */
            name: string | null;
            /** Tags */
            tags: string | null;
            /** Factory Name */
            factory_name: string | null;
            /** Icon */
            icon: string | null;
            /** Factory Map Icon */
            factory_map_icon: string | null;
            /** Factory Hud Icon */
            factory_hud_icon: string | null;
            /** Tier */
            tier: number | null;
            /** Priority */
            priority: number | null;
        };
        /** WareSummary */
        WareSummary: {
            /** Ware Id */
            ware_id: string;
            /** Name */
            name: string;
            /** Group Id */
            group_id: string | null;
            /** Transport */
            transport: string | null;
            /** Volume */
            volume: number;
            /** Price Avg */
            price_avg: number | null;
            /** Tags */
            tags: string | null;
            /** Icon Url */
            icon_url: string | null;
        };
        /** ZoneSummary */
        ZoneSummary: {
            /** Zone Id */
            zone_id: string;
            /** Sector Id */
            sector_id: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Z */
            z?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_wares_api_v1_wares_get: {
        parameters: {
            query?: {
                group?: string | null;
                transport?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WareSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ware_api_v1_wares__ware_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ware_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WareDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_faction_relations_api_v1_faction_relations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllFactionRelation"][];
                };
            };
        };
    };
    list_factions_api_v1_factions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactionSummary"][];
                };
            };
        };
    };
    get_faction_api_v1_factions__faction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_faction_relations_api_v1_factions__faction_id__relations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactionRelation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_licences_api_v1_licences_get: {
        parameters: {
            query?: {
                faction_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactionLicence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clusters_api_v1_map_clusters_get: {
        parameters: {
            query?: {
                owner_faction?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sectors_api_v1_map_sectors_get: {
        parameters: {
            query?: {
                cluster_id?: string | null;
                owner_faction?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_api_v1_map_sectors__sector_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gates_api_v1_map_gates_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zones_api_v1_map_zones_get: {
        parameters: {
            query?: {
                sector_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_zones_api_v1_map_sectors__sector_id__zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_api_v1_map_resources_get: {
        parameters: {
            query?: {
                /** @description Filter by ware (ore, silicon, nividium, hydrogen, helium, methane, ice) */
                ware?: string | null;
                /** @description Filter by sector macro ID */
                sector_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_resources_api_v1_map_sectors__sector_id__resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions_api_v1_map_regions_get: {
        parameters: {
            query?: {
                cluster_id?: string | null;
                sector_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_superhighways_api_v1_map_superhighways_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuperhighwaySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modules_api_v1_modules_get: {
        parameters: {
            query?: {
                /** @description Filter by kind: production, habitation, storage, dock, defence, connectionmodule */
                kind?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_api_v1_modules__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ships_api_v1_ships_get: {
        parameters: {
            query?: {
                class_id?: string | null;
                faction_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ship_api_v1_ships__ship_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_npc_stations_api_v1_npc_stations_get: {
        parameters: {
            query?: {
                /** @description Filter by owner faction ID */
                owner?: string | null;
                /** @description Filter by tag, e.g. shipyard, wharf, equipmentdock */
                tag?: string | null;
                /** @description Filter by location_sector (case-insensitive) */
                sector?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NpcStationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_npc_station_api_v1_npc_stations__station_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NpcStationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_loadouts_api_v1_loadouts_get: {
        parameters: {
            query?: {
                /** @description Filter by ship macro ID */
                ship_macro?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadoutDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loadout_api_v1_loadouts__loadout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loadout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadoutDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_equip_mods_api_v1_equipment_mods_get: {
        parameters: {
            query?: {
                /** @description Filter by category: weapon, engine, shield, ship */
                category?: string | null;
                /** @description Filter by stat type e.g. damage, cooling */
                stat?: string | null;
                /** @description Filter by quality tier 1–3 */
                quality?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipModSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equip_mod_api_v1_equipment_mods__ware_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ware_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipModDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_terraform_stats_api_v1_terraform_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerraformStat"][];
                };
            };
        };
    };
    list_terraform_project_groups_api_v1_terraform_project_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerraformProjectGroup"][];
                };
            };
        };
    };
    list_terraform_projects_api_v1_terraform_projects_get: {
        parameters: {
            query?: {
                group_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerraformProjectSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_terraform_project_api_v1_terraform_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerraformProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ware_groups_api_v1_ware_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WareGroup"][];
                };
            };
        };
    };
    get_ware_group_api_v1_ware_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WareGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diplo_actions_api_v1_diplomacy_actions_get: {
        parameters: {
            query?: {
                /** @description Filter by category: negotiation | espionage | interference */
                category?: string | null;
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiploAction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diplo_action_api_v1_diplomacy_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiploAction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diplo_gifts_api_v1_diplomacy_gifts_get: {
        parameters: {
            query?: {
                faction_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiploGift"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_ranks_api_v1_diplomacy_agent_ranks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRank"][];
                };
            };
        };
    };
    list_drop_lists_api_v1_drops_lists_get: {
        parameters: {
            query?: {
                /** @description ship | lockbox | asteroid | crystal | story | masstraffic | other */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropList"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drop_list_api_v1_drops_lists__list_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropListDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ware_drop_sources_api_v1_drops_wares__ware_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ware_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropSource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
